project_id = "csdagwvbuurumpgrqweh"

[functions.apply-move]
verify_jwt = false

[functions.new-game]
verify_jwt = false

[functions.current-position]
verify_jwt = false

[functions.legal-moves]
verify_jwt = false